acid-block | Replace pkg_resources to importlib_resources | Drop support for python 3.8
openedx/acid-block pull request #187
Opened 2024-09-25 06:42 UTC by ttqureshi

# Overview
This PR:
- replaces `pkg_resources` api from `importlib_resources` api
- drops support for `python 3.8` and add support for `python 3.11`
---
Tickets:
- [Move on from deprecated pkg_resources api](https://github.com/openedx/acid-block/issues/179)
- [Drop Python 3.8 & Add Support for Python 3.12](https://github.com/openedx/acid-block/issues/184)

Followed [this](https://importlib-resources.readthedocs.io/en/latest/migration.html) migration guide.

## Testing
I have tested the changes against the following steps:
- Install the `acid-block` to `xblock-sdk`.
- Functional testing

## Screenshots
### `XBlock Acid single block test`
<img width="854" alt="image" src="https://github.com/user-attachments/assets/e10bae39-189e-4512-9720-596903b1b472">

### `XBlock Acid Parent test`
<img width="779" alt="image" src="https://github.com/user-attachments/assets/a8434ae9-cdb9-419f-b337-ee10b0388ad0">

2024-09-27 11:56 UTC, farhan requested changes
1 change

2024-09-27 11:56 UTC, farhan commented on acid/acid.py
> +    from xblock.utils.resources import ResourceLoader
I think it should be in separate try catch

2024-09-27 15:07 UTC, feanil approved these changes
Please bump the version so we can also do a new release.

2024-09-30 06:08 UTC, ttqureshi commented
> Please bump the version so we can also do a new release.

ok 👍

2024-09-30 07:32 UTC, farhan approved these changes

2024-10-01 13:49 UTC, merged